ktor:
  application:
    modules:
      - pl.chodan.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
  database:
    url: "$DATABASE_URL:jdbc:postgresql://localhost:61500/mydb"
    user: "$DATABASE_USER:myuser"
    password: "$DATABASE_PASSWORD:mypassword"
    driver: "org.postgresql.Driver"
  cors:
    allowedHosts: "$HOSTS:localhost:8080, localhost:5173, localhost:8081"


keycloak:
  url: "$KEYCLOAK_URL:http://localhost:8081"
  clientId: "$KEYCLOAK_CLIENT_ID:mieszkanie_client_id"
  realm: "$KEYCLOAK_REALM:mieszkanie_realm"
  tokenPath: protocol/openid-connect/token